openapi: 3.0.0
info:
  title: OpenAI API
  version: '2024-01-04'
  description: |
    OpenAI API specification for various endpoints including Chat, Assistants, Files, and more.

servers:
  - url: https://api.openai.com/v1

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer

paths:
  /chat/completions:
    post:
      summary: Create chat completion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model
                - messages
              properties:
                model:
                  type: string
                  description: ID of the model to use
                messages:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum: [system, user, assistant]
                      content:
                        type: string
                temperature:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 2
                  default: 1